# Generated by Django 6.0.2 on 2026-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category_id', models.CharField(blank=True, max_length=64, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('alert_qty', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('location', models.CharField(default='Default', max_length=255)),
                ('sale_unit', models.CharField(default='Sale Unit', max_length=64)),
                ('extra_units', models.CharField(default='Extra Units', max_length=64)),
                ('base_unit', models.CharField(default='Base Unit', max_length=64)),
                ('purchase_unit', models.CharField(default='Purchase Unit', max_length=64)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('days_in_expiry', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
