# Generated by Django 6.0.2 on 2026-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caste',
            name='name_urdu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
