# Generated by Django 6.0.2 on 2026-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_branch_full_name_urdu_customer_father_name_urdu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
