# Generated by Django 6.0.2 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0004_customer_father_name_guarantor_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
