# Generated by Django 6.0.2 on 2026-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0005_customer_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
