# Generated by Django 6.0.2 on 2026-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0006_vehicle_engine_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='engine',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='frame',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='power',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
