# Generated by Django 6.0.2 on 2026-04-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0007_vehiclemodel_add_power_engine_frame_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='motors.invoice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.vehicle')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
    ]
