# Generated by Django 6.0.2 on 2026-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0008_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
