# Generated by Django 6.0.2 on 2026-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0009_vehicle_purchase_price_vehicle_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caste',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='installment',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='letter',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclepower',
            name='synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='synced',
            field=models.IntegerField(default=0),
        ),
    ]
