# Generated by Django 6.0.2 on 2026-04-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0010_area_synced_branch_synced_caste_synced_city_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motors.guarantor'),
        ),
    ]
