# Generated by Django 6.0.2 on 2026-05-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0011_invoice_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name_urdu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_urdu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
