# Generated by Django 6.0.2 on 2026-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0012_area_name_urdu_city_name_urdu_customer_reg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category_id', models.CharField(blank=True, max_length=64, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('alert_qty', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('location', models.CharField(default='Default', max_length=255)),
                ('sale_unit', models.CharField(default='Sale Unit', max_length=64)),
                ('extra_units', models.CharField(default='Extra Units', max_length=64)),
                ('base_unit', models.CharField(default='Base Unit', max_length=64)),
                ('purchase_unit', models.CharField(default='Purchase Unit', max_length=64)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('days_in_expiry', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='to_branch',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='guarantor',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='guarantor',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='power',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='PaymentVoucher',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ReceiptVoucher',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Caste',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Guarantor',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='StockTransfer',
        ),
        migrations.DeleteModel(
            name='VehicleColor',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehiclePower',
        ),
        migrations.DeleteModel(
            name='VehicleBrand',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
    ]
