# Generated by Django 6.0.2 on 2026-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapi', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SALES_AGENT', 'Sales Agent'), ('ACCOUNTANT', 'Accountant'), ('STAFF', 'Staff')], default='ADMIN', max_length=20),
        ),
    ]
