# Generated by Django 6.0.2 on 2026-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapi', '0007_unit_base_unit_unit_base_unit_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManager',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area', models.CharField(default='None', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'area_managers',
            },
        ),
    ]
